PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>

select distinct ?Concept ?Type where {
    {?_entity_iri dct:subject* ?Concept . bind ("C" as ?Type) }
    UNION
    {?_entity_iri rdf:type* ?Concept . bind ("T" as ?Type) }
}