# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:
  publish:
    name: Publish to docker registry
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker Build & Push to Github Container Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./Dockerfile
          registry: docker.pkg.github.com
          image_name: bme-mit-iet/iet-hf2021-csapat1234/iet
          image_tag: latest
          build_extra_args: --target prod
          pull_image_and_stages: true
          push_git_tag: true
          push_image_and_stages: true